// packages/vue/src/components/Book.vue
<script setup lang="ts">
import { watch, computed, unref } from "vue";
import { useBook } from "../composable/useBook";

const { result, loading, error } = useBook();
const books = computed(() => unref(result).books);
</script>

<template>
  <div>Book</div>
  <div v-if="loading">Loading……</div>

  <div v-else v-for="book in books">
    <div>title: {{ book.title }}</div>
    <div>author: {{ book.author }}</div>
  </div>
</template>

// packages/client/src/components/book.tsx
import { useQuery } from '@apollo/client'
import { GET_BOOKS } from '../schema/getBooks'

interface Books {
  title: string
  author: string
}

function Book() {
  const { loading, error, data } = useQuery(GET_BOOKS)

  if (loading) return <p>Loading...</p>
  if (error) return <p>Error 😢</p>

  return data.books.map(({ title, author }: Books) => (
    <div>
      <div>book: {title}</div>
      <span>author: {author}</span>
    </div>
  ))
}

export default Book
